CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    LAST_LOGIN TIMESTAMP DEFAULT NOW(),
    PASSWORD_HASH text not null,
    CREATED TIMESTAMP DEFAULT NOW(),
    UPDATED TIMESTAMP DEFAULT NOW()
);