CREATE TABLE MESSAGES (
    ID SERIAL PRIMARY KEY NOT NULL,
    TEXT TEXT NOT NULL,
    CREATED TIMESTAMP DEFAULT NOW(),
    UPDATED TIMESTAMP DEFAULT NOW(),
    DELIVERED TIMESTAMP NULL,
    SENDER INT references USERS(ID),
    RECEIVER INT references USERS(ID)
);