db:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: some-password
  database: some-database
meta:
  migrations:
    folder_path: libs/infrastructure/database/migrations
  secret_key: some-secret-key
sessions:
  expiration: 3600